#!/bin/bash

if [ "$(id -u)" != "0" ];
 then
  echo "This script must be run as root" 1>&2
 exit 1
fi

export AWS_ACCESS_KEY_ID=""
export AWS_SECRET_ACCESS_KEY=""
export ZONE=""
export TTL="60"

DNS_RECORD="$(hostname)"
SERVER_IP=$(ip -o -4 addr show eth0 | awk -F '[ /]+' '/global/ {print $4}')

cli53 rrcreate "$ZONE" "$DNS_RECORD" A "$SERVER_IP" --replace --ttl "$TTL"

exit 0
