#!/bin/bash

export AWS_ACCESS_KEY_ID=""
export AWS_SECRET_ACCESS_KEY=""
export ZONE=""
export TTL="60"

export DNS_RECORD="$(hostname)"
export SERVER_IP=$(ip -o -4 addr show eth0 | awk -F '[ /]+' '/global/ {print $4}')

cli53 rrcreate "$ZONE" "$DNS_RECORD" A "$SERVER_IP" --replace --ttl "$TTL"

exit 0
