---
- hosts: "{{ hosts_group }}"
  vars_files:
    - ../../vars/common.vars.yml
  become: yes
  become_method: sudo

  tasks:
  - name: Reboot core
    action: shell sleep 2 && reboot
    async: 1
    poll: 0
    ignore_errors: true
