---
- hosts: all
  vars_files:
    - ../vars/common.vars.yml
  remote_user: alarm
  become: yes
  become_user: root
  become_method: su
  gather_facts: false

  tasks:
  - name: Install python2.7
    raw: pacman -Sy --noconfirm --needed python2

  - include: ../modules/base/generic/skel.yml
  - include: ../modules/base/users/users.yml
  - include: ../modules/base/ssh/ssh.yml
  - include: ../modules/base/sudo/sudo.yml
  - include: ../modules/base/pacman/pacman.yml
  - include: ../modules/base/pacman/pacman.special.yml
  - include: ../modules/base/pacman/pacman.full-update.yml
