---
- hosts: "{{ hosts_group }}"
  vars_files:
    - ../vars/common.vars.yml
  become: yes
  become_method: sudo

  tasks:
  - include: ../modules/base/generic/skel.yml
  - include: ../modules/base/users/users.yml
  - include: ../modules/base/ssh/ssh.yml
  - include: ../modules/base/sudo/sudo.yml
  - include: ../modules/base/pacman/pacman.yml
  - include: ../modules/base/pacman/pacman.base-install.yml
  - include: ../modules/base/pacman/pacman.special.yml
  - include: ../modules/base/generic/swap.yml
  - include: ../modules/base/generic/dirs.yml
  - include: ../modules/base/generic/scripts.yml
  - include: ../modules/base/generic/clock.yml
  - include: ../modules/base/generic/motd.yml
  - include: ../modules/base/generic/etc.yml
  - include: ../modules/base/generic/etc.special.yml
  - include: ../modules/base/network/hostname.yml
  - include: ../modules/base/generic/services.yml
  - include: ../modules/base/pacman/pacman.cleanup.yml

  handlers:
  - include: ../modules/base/ssh/ssh.handlers.yml
